config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index] do
    collection do
      get :edit_password
      patch :update_password
    end
  end

  resources :posts
  resources :photos, only: [:new, :create, :index, :destroy]
  resources :documents
  resources :products do
    post :charge, on: :collection
  end
  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<div class='container'>
  <div class='row'>
    <center><h1>Welcome To Shirjeel's Playground</h1></center>
  </div>
  <div class='row well'>
    <h3><%= link_to('Documents', documents_path) %></h3>
    <p>Test generation of PDF and watermarking it. Uses <%= link_to('Prawn', 'https://github.com/prawnpdf/prawn') %> and <%= link_to('CombinePDF', 'https://github.com/boazsegev/combine_pdf') %>.<p>
  </div>
  <div class='row well'>
    <h3><%= link_to('Photos', photos_path) %></h3>
    <p>Test paperclip and integration with different storage systems like local, dropbox, s3. Uses <%= link_to('Paperclip', 'https://github.com/thoughtbot/paperclip') %>, <%= link_to('Paperclip-Dropbox', 'https://github.com/janko-m/paperclip-dropbox') %> and <%= link_to('AWS-SDK', 'https://github.com/aws/aws-sdk-ruby') %>.<p>
  </div>
  <div class='row well'>
    <h3><%= link_to('Posts', posts_path) %></h3>
    <p>Test inline TeX math rendering. Uses <%= link_to('KaTeX', 'https://github.com/Khan/KaTeX') %> and <%= link_to('ExecJS', 'https://github.com/rails/execjs') %>.<p>
  </div>
  <div class='row well'>
    <h3><%= link_to('Products', products_path) %></h3>
    <p>Test stripe checkout and have multiple buttons on same page. Uses <%= link_to('Stripe', 'https://github.com/stripe/stripe-ruby') %>.<p>
  </div>
  <div class='row well'>
    <h3><%= link_to('Users', users_path) %></h3>
    <p>Test different devise scenarios. Uses <%= link_to('Devise', 'https://github.com/plataformatec/devise') %>.<p>
  </div>
</div>