config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index] do
    collection do
      get :edit_password
      patch :update_password
    end
  end

  resources :posts
  resources :photos, only: [:new, :create, :index, :destroy]
  resources :documents
  resources :products do
    post :charge, on: :collection
  end
  root to: 'welcome#index'
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                    :integer          not null, primary key
#  document_file_name    :string
#  document_content_type :string
#  document_file_size    :integer
#  document_updated_at   :datetime
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  email                 :string
#

class Document < ActiveRecord::Base
  has_attached_file :document, path: ':rails_root/public/system/uploads/:attachment/:id/:filename', url: '/system/uploads/:attachment/:id/:filename'
  validates_attachment :document, content_type: { content_type: 'application/pdf' }, presence: true

  def path
    document.path
  end

  def url
    document.url
  end

  def filename
    document_file_name.split('.').first
  end

  def watermark_pdf
    doc = CombinePDF.load(path)
    tmp_doc = 'tmp/watermark.pdf'
    
    Prawn::Document.generate(tmp_doc) do |pdf|
      # Center Rotated
      # pdf.repeat :all do
      #   pdf.fill_color 'D3D3D3'
      #   pdf.text_box email, align: :center, valign: :center, size: 24, rotate: 45, at: [100, 450]
      # end

      # Bottom Right Corner
      # pdf.repeat :all do
      #   pdf.fill_color 'D3D3D3'
      #   pdf.text_box email, align: :right, valign: :bottom, size: 16
      # end
      
      # (doc.pages.count - 1).times do 
      #   pdf.start_new_page
      # end
    end

    CombinePDF.load(tmp_doc)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.order('created_at')
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      flash[:success] = "The document was added!"
      redirect_to documents_path
    else
      render 'new'
    end
  end

  def show
    @document = Document.find(params[:id])
    @document.watermark_pdf
    watermark_pdf = @document.watermark_pdf
    pdf = CombinePDF.load @document.path
    watermark_pdf.pages.each_with_index do |page, index|
      page << pdf.pages[index]
    end
    @watermark_document = "tmp/tmp_#{@document.document_file_name}"
    watermark_pdf.save @watermark_document
    send_file(@watermark_document, disposition: 'inline', type: 'application/pdf', x_sendfile: true)
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    flash[:success] = "The document was destroyed."
    redirect_to documents_path
  end

  private

  def document_params
    params.require(:document).permit(:email, :document)
  end
end

app/views/documents/_document.html.erb
<div class='row'>
  <h3>Email: <%= document.email %></h3>
  <%= link_to 'Show Document', document_path(document), target: '_blank', class: 'btn btn-primary' %>
  <%= link_to 'View Document', document.url, target: '_blank', class: 'btn btn-info' %>
  <%= link_to 'Remove', document_path(document), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/documents/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header"><h1>Documents</h1></div>
    <%= link_to 'Create Document', new_document_path, class: 'btn btn-primary pull-right' %>
  </div>
  <%= render @documents %>
</div>

app/views/documents/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header"><h1>Upload Document</h1></div>

    <%= form_for @document do |f| %>
      <%= render 'shared/errors', object: @document %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :document %>
        <%= f.file_field :document, class: 'form-control'%>
      </div>

      <%= f.submit 'Upload', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>