config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index] do
    collection do
      get :edit_password
      patch :update_password
    end
  end

  resources :posts
  resources :photos, only: [:new, :create, :index, :destroy]
  resources :documents
  resources :products do
    post :charge, on: :collection
  end
  root to: 'welcome#index'
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id                 :integer          not null, primary key
#  title              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Photo < ActiveRecord::Base
  has_attached_file :image,
  styles: { thumb: ["64x64#", :jpg], original: ['500x500>', :jpg] },
  convert_options: { thumb: "-quality 75 -strip", original: "-quality 85 -strip" },
  ## LOCAL FILE
  # path: ':rails_root/public/system/uploads/:attachment/:id/:style/:filename',
  # url: '/system/uploads/:attachment/:id/:style/:filename'
  ## DROPBOX
  # storage: :dropbox,
  # dropbox_credentials: Rails.root.join('config', 'dropbox.yml'),
  # dropbox_visibility: 'private',
  # path: 'App/ShirjeelPlayground/:id/:style/:filename'
  ## S3
  storage: :s3,
  s3_credentials: Rails.root.join('config','aws.yml')

  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.order('created_at')
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "The photo was added!"
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:success] = "The photo was destroyed."
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(photo.image.url(:thumb), class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title %></h4>
    <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
  </div>
</div>

app/views/photos/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header"><h1>Photos</h1></div>
    <%= link_to 'Create Photo', new_photo_path, class: 'btn btn-primary pull-right' %>
    <%= render @photos %>
  </div>
</div>

app/views/photos/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="page-header"><h1>Upload Photo</h1></div>

    <%= form_for @photo do |f| %>
      <%= render 'shared/errors', object: @photo %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control'%>
      </div>

      <%= f.submit 'Upload', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>